import test from "node:test";
import assert from "node:assert/strict";
import { validateRent2BuySemantics, RENT2BUY_COLLECTION_SENTENCE, RENT2BUY_SEPARATION_SENTENCE, validateMarkdownStructure } from "../lib/rent2BuyRules.js";
import { buildCorrectionPreview, normalizeCorrectionProposal } from "../lib/publishingCorrections.js";

const usefulContent = Array.from({ length: 220 }, (_, index) => `guidance${index + 1}`).join(" ");
const body=`## Introduction\n\n${RENT2BUY_SEPARATION_SENTENCE}\n\n${usefulContent}\n\n## Key Features\n\n${RENT2BUY_COLLECTION_SENTENCE}\n\n## Practical Next Steps\n\n1. Apply\n2. Review eligibility\n3. Collect the vehicle\n\nApply for Rent2Buy`;
const article=(overrides={})=>({id:"r2b",title:"Rent2Buy vans",seo_title:"Rent2Buy vans",meta_description:"Rent2Buy agreement information",excerpt:"Review eligibility and agreement terms.",category:"Rent2Buy",article_type:"guide",content_markdown:body,faq_json:[{question:"How does eligibility work?",answer:"Review the eligibility requirements before proceeding."}],cta:"Apply for Rent2Buy",internal_link_suggestions:[{id:"link-1",anchor_text:"Rent2Buy application",destination_url:"/apply",status:"accepted"}],...overrides});

test("metadata, excerpt, FAQs, CTA and link anchors are scanned",()=>{const result=validateRent2BuySemantics(article({meta_description:"Traditional finance options",excerpt:"APR may apply",faq_json:[{question:"Which lender?",answer:"Ask about rates"}],cta:"Start a finance application",internal_link_suggestions:[{anchor_text:"Finance options",destination_url:"/apply"}]}));assert.equal(result.rent2buy_semantic_valid,false);assert.deepEqual(new Set(result.rent2buy_semantic_errors.map((item)=>item.section)),new Set(["Meta description","Excerpt","FAQ 1","CTA","Internal-link anchor 1"]));});

test("validator evaluates corrected proposed fields rather than stale originals",()=>{const original=article({meta_description:"Traditional finance options",faq_json:[{question:"Which lender?",answer:"APR details"}],cta:"Finance application",internal_link_suggestions:[{id:"link-1",anchor_text:"Finance options",destination_url:"/apply",status:"accepted"}]});const proposed={...original,meta_description:"Rent2Buy agreement information",faq_json:[{question:"How does eligibility work?",answer:"Review the agreement terms."}],cta:"Apply for Rent2Buy",internal_link_suggestions:[{anchor_text:"Rent2Buy application",destination_url:"https://changed.invalid"}],changes:[],removed_links:[],manual_confirmation_required:[],removed_sections:[],removal_reasons:[],removed_section_word_counts:[]};const normalized=normalizeCorrectionProposal(original,proposed).corrected_article;assert.equal(validateRent2BuySemantics(normalized).rent2buy_semantic_valid,true);assert.equal(normalized.internal_link_suggestions[0].destination_url,"/apply");assert.equal(normalized.internal_link_suggestions[0].anchor_text,"Rent2Buy application");});

test("exact company name is allowed as identification",()=>{assert.equal(validateRent2BuySemantics(article({excerpt:"Van Finance Company provides this information for Rent2Buy customers."})).rent2buy_semantic_valid,true);});

test("finance claims containing company name remain blocked",()=>{const phrases=["Van Finance Company finance application","Finance options from Van Finance Company","Lender panel available through Van Finance Company"];for(const excerpt of phrases)assert.equal(validateRent2BuySemantics(article({excerpt})).rent2buy_semantic_valid,false);});

test("required sentences appear before CTA",()=>{const ctaIndex=body.indexOf("Apply for Rent2Buy");assert.ok(body.indexOf(RENT2BUY_SEPARATION_SENTENCE)<ctaIndex);assert.ok(body.indexOf(RENT2BUY_COLLECTION_SENTENCE)<ctaIndex);});

test("complete multi-field proposal can reach correction_complete true",()=>{const original=article({meta_description:"Traditional finance options",excerpt:"Test the van before buying",faq_json:[{question:"Which lender?",answer:"APR details"}],cta:"Finance application",internal_link_suggestions:[{id:"link-1",anchor_text:"Finance options",destination_url:"/apply",status:"accepted"}]});const proposed={...article(),changes:["Corrected all Rent2Buy fields"],removed_links:[],manual_confirmation_required:[],removed_sections:[],removal_reasons:[],removed_section_word_counts:[]};const preview=buildCorrectionPreview({originalArticle:original,proposed,safetyOptions:{ignoreAssessmentFreshness:true}});assert.equal(preview.rent2buy_semantic_valid,true);assert.equal(preview.markdown_structure_valid,true);assert.equal(preview.correction_complete,true);});

test("field-specific issues are grouped without duplicate phrase spam",()=>{const result=validateRent2BuySemantics(article({meta_description:"Finance finance finance options"}));const meta=result.rent2buy_semantic_errors.filter((item)=>item.section==="Meta description");assert.ok(meta.length<=2);});

test("Markdown remains valid",()=>assert.equal(validateMarkdownStructure(body,"Apply for Rent2Buy").markdown_structure_valid,true));

test("original article remains unchanged until acceptance and no Wix approval occurs",()=>{const original=article({meta_description:"Finance options"});const snapshot=structuredClone(original);normalizeCorrectionProposal(original,{...article(),changes:[],removed_links:[],manual_confirmation_required:[],removed_sections:[],removal_reasons:[],removed_section_word_counts:[]});assert.deepEqual(original,snapshot);assert.equal(original.wix_sync_status,undefined);assert.notEqual(original.status,"approved");});