import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { auditPublishedArticles, evaluatePublishingSafety } from "../lib/publishingSafety.js";
import { classifyArticleProduct } from "../lib/rent2BuyRules.js";
import { loadKnowledgeHub } from "../services/knowledgeHub.js";
import { loadEditorialEngine, analyseEditorialArticle, recordArticleRevision } from "../services/editorialEngine.js";
import { acceptPublishingCorrection, proposeBulkPublishingCorrections, proposePublishingCorrection, savePublishingCorrectionScope } from "../services/publishingCorrections.js";

const SCOPE_LABELS = { rent2buy: "Rent2Buy", finance: "Van Finance", both: "Both / Comparison" };
const STATUS_LABELS = { ready: "Ready to accept", review: "Review and confirm", blocked: "Blocked — material corrections required" };
function articleTitleFromPage() { const editor = [...document.querySelectorAll(".panel")].find((panel) => panel.querySelector(".eyebrow")?.textContent?.trim() === "Article Editor"); return editor?.querySelector("h3")?.textContent?.trim() || ""; }
function displayItem(item) { if (typeof item === "string") return item; const location = [item?.field, item?.section, item?.column].filter(Boolean).join(" · ") || "Article"; const context = item?.product_context ? ` [${item.product_context}]` : ""; const issue = item?.phrase || item?.message || item?.error_type || item?.type || "Issue"; const values = item?.original_protected_value !== undefined || item?.proposed_protected_value !== undefined ? ` Original: ${item.original_protected_value || "—"} · Proposed: ${item.proposed_protected_value || "—"}.` : ""; return `${location}${context}: ${issue}.${values}${item?.excerpt ? ` — ${item.excerpt}` : ""}`; }
function ListNotice({ title, items }) { if (!items?.length) return null; return <div className="notice" style={{ marginTop: 10 }}><strong>{title}</strong><ul>{items.map((item, index) => <li key={`${displayItem(item)}-${index}`}>{displayItem(item)}</li>)}</ul></div>; }
function Field({ label, value }) { return <div style={{ marginBottom: 10 }}><strong>{label}</strong><pre style={{ whiteSpace: "pre-wrap", margin: 0 }}>{value || "—"}</pre></div>; }
function DiffColumn({ title, article }) { const faqText = (article?.faq_json || []).map((item, index) => `${index + 1}. ${item?.question || ""}\n${item?.answer || ""}`).join("\n\n"); const linkText = (article?.internal_link_suggestions || []).map((item) => `${item?.anchor_text || item?.label || ""} → ${item?.destination_url || item?.url || ""}`).join("\n"); return <div className="notice"><h4>{title}</h4><Field label="Article title" value={article?.title} /><Field label="SEO title" value={article?.seo_title} /><Field label="Meta description" value={article?.meta_description} /><Field label="Excerpt" value={article?.excerpt} /><Field label="Article body" value={article?.content_markdown} /><Field label="FAQs" value={faqText} /><Field label="CTA" value={article?.cta} /><Field label="Internal-link anchors" value={linkText} /></div>; }
function ResultSummary({ proposal }) { const status = proposal?.review_status || (proposal?.correction_complete ? "ready" : "blocked"); return <div className={`notice ${status === "blocked" ? "notice--error" : ""}`} style={{ marginTop: 12 }}><strong>{STATUS_LABELS[status]}</strong><p>{proposal?.automatic_repairs_count || 0} automatic repairs completed · {proposal?.claim_confirmation_required ? 1 : 0} claim requires confirmation · {proposal?.editorial_warning_count || 0} editorial warning{proposal?.editorial_warning_count === 1 ? "" : "s"}</p><small>Product scope: {SCOPE_LABELS[proposal?.product_scope] || proposal?.product_scope} · Content retained: {proposal?.content_retained_percent}%</small></div>; }

function TechnicalDetails({ proposal }) {
  return <details style={{ marginTop: 12 }}><summary><strong>Show technical details</strong></summary>
    <ListNotice title="Material blocks" items={proposal.remaining_hard_blocks} />
    <ListNotice title="Review warnings" items={proposal.review_warnings} />
    <ListNotice title="Protected-value errors" items={proposal.protected_value_errors} />
    <ListNotice title="Approved-sentence errors" items={proposal.approved_sentence_errors} />
    <ListNotice title="Targeted repair text errors" items={proposal.targeted_repair_text_errors} />
    <ListNotice title="Rent2Buy semantic issues" items={proposal.remaining_semantic_errors || proposal.rent2buy_semantic_errors} />
    <ListNotice title="Comparison structure issues" items={proposal.comparison_structure_errors} />
    <ListNotice title="Markdown structure issues" items={proposal.markdown_structure_errors} />
    {proposal.targeted_repairs_applied ? <div className="notice" style={{ marginTop: 10 }}><strong>Targeted repairs</strong><p>Fields: {(proposal.repaired_fields || []).join(", ") || "None"}</p>{proposal.removed_faqs?.length ? <p>FAQs removed: {proposal.removed_faqs.join(", ")}</p> : null}{proposal.rewritten_faqs?.length ? <p>FAQs rewritten: {proposal.rewritten_faqs.join(", ")}</p> : null}</div> : null}
  </details>;
}

function CorrectionPanel({ articleTitle }) {
  const [article, setArticle] = useState(null); const [assessment, setAssessment] = useState(null); const [businessKnowledge, setBusinessKnowledge] = useState([]); const [scope, setScope] = useState("rent2buy"); const [savedScope, setSavedScope] = useState("rent2buy"); const [proposal, setProposal] = useState(null); const [status, setStatus] = useState("idle"); const [message, setMessage] = useState(""); const [contentLossConfirmed, setContentLossConfirmed] = useState(false); const [claimsConfirmed, setClaimsConfirmed] = useState(false);
  useEffect(() => { let active = true; Promise.all([loadKnowledgeHub(), loadEditorialEngine()]).then(([hub, editorial]) => { if (!active) return; const found = (hub.articles || []).find((item) => item.title === articleTitle); const latestAssessment = (editorial.assessments || []).filter((item) => item.article_id === found?.id).sort((a, b) => new Date(b.created_at) - new Date(a.created_at))[0] || null; const detectedScope = classifyArticleProduct(found || {}, latestAssessment?.effective_intent || {}); setArticle(found || null); setBusinessKnowledge(hub.business_sections || []); setAssessment(latestAssessment); setScope(detectedScope); setSavedScope(detectedScope); }).catch((error) => setMessage(error.message || "Correction context could not be loaded.")); return () => { active = false; }; }, [articleTitle]);
  const safety = useMemo(() => evaluatePublishingSafety(article || {}, { assessment, businessKnowledge, scopeOverride: savedScope }), [article, assessment, businessKnowledge, savedScope]);
  const needsCorrection = safety.hard_blocked || safety.requires_manual_claim_review || safety.review_warnings?.length || Object.values(safety.checks || {}).some((value) => value !== "passed");
  async function saveScope() { if (!article || scope === savedScope) return; setStatus("working"); try { const result = await savePublishingCorrectionScope(article.id, scope); setArticle((current) => ({ ...current, generation_metadata: result.article?.generation_metadata || { ...(current?.generation_metadata || {}), product_scope_override: scope } })); setSavedScope(scope); setProposal(null); setMessage("Product scope saved. Changing product scope will rerun the relevant publishing rules."); } catch (error) { setScope(savedScope); setMessage(error.message || "Product scope could not be saved."); } finally { setStatus("idle"); } }
  async function propose(reasons = []) { setStatus("working"); setMessage("Running AI correction, targeted repair, Markdown normalisation and full validation…"); setContentLossConfirmed(false); setClaimsConfirmed(false); try { const result = await proposePublishingCorrection(article.id, reasons, savedScope); setProposal(result.proposal); setStatus("ready"); setMessage(STATUS_LABELS[result.proposal.review_status || "blocked"]); } catch (error) { setStatus("idle"); setMessage(error.message || "AI correction could not be prepared."); } }
  async function accept() { if (!proposal?.correction_complete) return; setStatus("working"); try { await recordArticleRevision(article.id, "ai_safety_correction", "Original article preserved before accepted AI safety corrections."); await acceptPublishingCorrection(proposal, { contentLoss: contentLossConfirmed, claims: claimsConfirmed }); await analyseEditorialArticle(article.id); window.setTimeout(() => window.location.reload(), 500); } catch (error) { setStatus("ready"); setMessage(error.message || "Accepted corrections could not be saved."); } }
  if (!article || !needsCorrection) return null;
  const acceptDisabled = status === "working" || !proposal?.correction_complete || !proposal?.markdown_structure_valid || proposal?.rent2buy_semantic_valid === false || proposal?.comparison_structure_valid === false || proposal?.protected_values_valid === false || proposal?.targeted_repair_text_valid === false || (proposal?.content_loss_confirmation_required && !contentLossConfirmed) || (proposal?.claim_confirmation_required && !claimsConfirmed);
  return <div style={{ marginTop: 16 }}>
    <div className="notice"><strong>Product scope: {SCOPE_LABELS[savedScope] || savedScope}</strong><div className="card-actions" style={{ marginTop: 8 }}><select value={scope} disabled={status === "working"} onChange={(event) => setScope(event.target.value)} aria-label="Product scope"><option value="rent2buy">Rent2Buy</option><option value="finance">Van Finance</option><option value="both">Both / Comparison</option></select><button type="button" className="button button--ghost" disabled={status === "working" || scope === savedScope} onClick={saveScope}>Save Product Scope</button></div><small>Changing product scope will rerun the relevant publishing rules.</small></div>
    {!proposal ? <button type="button" className="button button--primary" disabled={status === "working" || scope !== savedScope} onClick={() => propose()}>Fix with AI</button> : null}
    {message ? <div className="notice" style={{ marginTop: 12 }}><strong>{message}</strong></div> : null}
    {proposal ? <><ResultSummary proposal={proposal} />
      {proposal.claim_confirmation_required ? <label className="notice" style={{ display: "block", marginTop: 12 }}><input type="checkbox" checked={claimsConfirmed} onChange={(event) => setClaimsConfirmed(event.target.checked)} /> I have reviewed and confirm the flagged business or financial claim.</label> : null}
      {proposal.content_loss_confirmation_required ? <label className="notice" style={{ display: "block", marginTop: 12 }}><input type="checkbox" checked={contentLossConfirmed} onChange={(event) => setContentLossConfirmed(event.target.checked)} /> I have reviewed and confirm the proposed content reduction.</label> : null}
      <TechnicalDetails proposal={proposal} />
      <details style={{ marginTop: 12 }}><summary><strong>Show before and after comparison</strong></summary><div className="knowledge-two-column" style={{ marginTop: 12 }}><DiffColumn title="Before" article={proposal.before} /><DiffColumn title="After" article={proposal.after} /></div></details>
      <div className="card-actions" style={{ marginTop: 12 }}><button type="button" className="button button--success" disabled={acceptDisabled} onClick={accept}>Accept Corrections</button>{proposal.review_status === "blocked" ? <button type="button" className="button button--primary" disabled={status === "working"} onClick={() => propose(proposal.remaining_hard_blocks || [])}>Regenerate Correction</button> : null}<button type="button" className="button button--ghost" disabled={status === "working"} onClick={() => { setProposal(null); setStatus("idle"); setMessage("Corrections discarded. The article was not changed."); }}>Discard Corrections</button></div>
    </> : null}
  </div>;
}

function BulkCorrectionPanel() {
  const [flagged, setFlagged] = useState([]); const [selected, setSelected] = useState([]); const [results, setResults] = useState([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function audit() { setBusy(true); try { const [hub, editorial] = await Promise.all([loadKnowledgeHub(), loadEditorialEngine()]); const items = auditPublishedArticles({ articles: hub.articles || [], assessments: editorial.assessments || [], businessKnowledge: hub.business_sections || [] }); setFlagged(items); setSelected([]); setMessage(`${items.length} flagged published article(s). Select up to 5 for correction proposals.`); } finally { setBusy(false); } }
  async function runBulk() { setBusy(true); try { const response = await proposeBulkPublishingCorrections(selected.slice(0, 5)); setResults(response.results || []); setMessage("Proposals prepared individually. Nothing was approved, accepted or sent to Wix."); } finally { setBusy(false); } }
  return <div style={{ marginTop: 12 }}><div className="card-actions"><button type="button" className="button button--ghost" disabled={busy} onClick={audit}>Select Published Articles for AI Fix</button>{flagged.length ? <button type="button" className="button button--primary" disabled={busy || !selected.length} onClick={runBulk}>Fix Flagged Articles with AI ({selected.length})</button> : null}</div>{message ? <div className="notice" style={{ marginTop: 8 }}>{message}</div> : null}{flagged.map((item) => <label key={item.article.id} className="notice"><input type="checkbox" checked={selected.includes(item.article.id)} disabled={!selected.includes(item.article.id) && selected.length >= 5} onChange={(event) => setSelected((current) => event.target.checked ? [...current, item.article.id].slice(0, 5) : current.filter((id) => id !== item.article.id))} /><strong>{item.article.title}</strong></label>)}{results.map((item) => { const resultStatus = item.proposal?.review_status || item.status || "blocked"; return <div className={`notice ${resultStatus === "blocked" ? "notice--error" : ""}`} key={item.article_id}><strong>{resultStatus === "ready" ? "Ready" : resultStatus === "review" ? "Review" : "Blocked"}</strong>{item.message ? <p>{item.message}</p> : null}</div>; })}</div>;
}
const mounted = new WeakSet();
export function installPublishingSafetyCorrections() { if (typeof document === "undefined") return; const mount = () => { [...document.querySelectorAll(".panel h3")].filter((heading) => heading.textContent?.trim() === "Publishing Safety Checks").forEach((heading) => { const panel = heading.closest(".panel"); if (!panel || mounted.has(panel)) return; const host = document.createElement("div"); panel.appendChild(host); mounted.add(panel); createRoot(host).render(<CorrectionPanel articleTitle={articleTitleFromPage()} />); }); const auditButton = [...document.querySelectorAll("button")].find((button) => button.textContent?.trim() === "Audit Published Articles"); const container = auditButton?.closest(".knowledge-table-wrap"); if (container && !container.querySelector("[data-publishing-correction-host='bulk']")) { const host = document.createElement("div"); host.dataset.publishingCorrectionHost = "bulk"; container.insertBefore(host, container.firstChild); createRoot(host).render(<BulkCorrectionPanel />); } }; mount(); new MutationObserver(mount).observe(document.body, { childList: true, subtree: true }); }
