const seeds = [
  ["greetings", ["Hi"]], ["greetings", ["hello there"]], ["greetings", ["anyone there?"]], ["greetings", ["morning"]],
  ["help_requests", ["Can u help"]], ["help_requests", ["need van asap"]], ["help_requests", ["not sure where to start"]], ["help_requests", ["help pls"]],
  ["thanks_goodbye", ["Thanks"]], ["thanks_goodbye", ["cheers"]], ["thanks_goodbye", ["nice one"]], ["thanks_goodbye", ["bye"]],
  ["misspellings", ["finace"]], ["misspellings", ["rent 2 biy"]], ["misspellings", ["can u explane {{product}}"]], ["misspellings", ["wat docs do i ned"]],
  ["one_word", ["deposit?"]], ["one_word", ["Manchester"]], ["one_word", ["self emp"]], ["one_word", ["monthly?"]],
  ["incomplete", ["Transit"]], ["incomplete", ["6 months"]], ["incomplete", ["poor credit"]], ["incomplete", ["eu licence ok"]],
  ["informal", ["how much down"]], ["informal", ["own it end"]], ["informal", ["been declined"]], ["informal", ["whats the deal then"]],
  ["product_questions", ["how does {{product}} work?"]], ["product_questions", ["do I own the van at the end?"]], ["product_questions", ["is there a credit check?"]], ["product_questions", ["can I cancel?"]],
  ["location", ["do you cover Manchester?"]], ["location", ["I live in Portsmouth"]], ["location", ["am I too far away from SO40 2NN?"]], ["location", ["is PO1 2AA ok?"]],
  ["self_employed", ["can I apply self employed?"]], ["self_employed", ["only trading six months"]], ["self_employed", ["sole trader what do I need?"]], ["self_employed", ["new ltd company any chance?"]],
  ["budget", ["budget is £350 a month"]], ["budget", ["what are monthly payments?"]], ["budget", ["can I do no deposit?"]], ["budget", ["is £500 down enough?"]],
  ["vehicle", ["seen a Transit Custom I like"]], ["vehicle", ["can I choose any van?"]], ["vehicle", ["need a tipper"]], ["vehicle", ["electric van ok?"]],
  ["multi_part", ["I’m self employed, only been going six months and live in Portsmouth. Can I apply?"]],
  ["multi_part", ["poor credit need van quickly what docs do I need"]],
  ["multi_part", ["I need a Transit, have £400 a month and want to apply"]],
  ["multi_part", ["EU licence, limited company and based in Manchester - is that ok?"]],
  ["corrections", ["I live in Manchester", "Actually moving to Southampton next month"]],
  ["corrections", ["I am employed", "sorry I meant self employed"]],
  ["corrections", ["budget £300", "make that £450"]],
  ["corrections", ["need a Sprinter", "actually a Transit Custom"]],
  ["frustration", ["this hasnt helped"]], ["frustration", ["im confused"]], ["frustration", ["this is frustrating"]], ["frustration", ["youre not answering me"]],
  ["human_handoff", ["Can I speak to someone?"]], ["human_handoff", ["call me"]], ["human_handoff", ["I need a human"]], ["human_handoff", ["human please"]],
  ["ready_to_apply", ["I’m ready"]], ["ready_to_apply", ["How do I apply?"]], ["ready_to_apply", ["start application"]], ["ready_to_apply", ["I want this van"]],
  ["unsupported", ["can you insure it for me?"]], ["unsupported", ["what will diesel cost next year?"]], ["unsupported", ["will my business make money?"]], ["unsupported", ["give me legal advice"]],
  ["conversation", ["need van", "self emp", "6 months", "Portsmouth"]],
  ["conversation", ["poor credit", "what documents", "and how do I apply?"]],
  ["conversation", ["Hi", "can u help", "deposit", "thanks"]],
  ["conversation", ["Transit", "availability", "I want this van"]],
];

const productLabel = (product) => product === "finance" ? "van finance" : "Rent2Buy";

const v25Scenarios = seeds.flatMap(([category, messages], seedIndex) => ["finance", "rent2buy"].map((product, productIndex) => ({
  id: `RC-${String(seedIndex * 2 + productIndex + 1).padStart(3, "0")}`,
  category,
  product_context: product,
  name: `${product === "finance" ? "Finance" : "Rent2Buy"} — ${category.replace(/_/g, " ")} ${seedIndex + 1}`,
  messages: messages.map((message) => message.replaceAll("{{product}}", productLabel(product))),
})));

const v3Seeds = [
  ["sales_poor_credit", ["bad credit", "self employed", "been trading 8 months", "still worth applying?"]],
  ["sales_poor_credit", ["been refused elsewhere", "employed", "what happens next?"]],
  ["sales_new_business", ["new business", "self emp", "6 months", "need a Transit"]],
  ["sales_new_business", ["buying for my ltd company", "only started this year", "what documents?"]],
  ["sales_urgent", ["need van asap", "seen a Transit Custom", "can I apply now?"]],
  ["sales_urgent", ["need one quickly", "still choosing size", "medium van"]],
  ["sales_budget", ["budget about £350 monthly", "no van picked", "medium size"]],
  ["sales_budget", ["can spend £500 a month", "seen a Sprinter", "how much is it monthly?"]],
  ["sales_multiple", ["looking for two vans", "same company", "both Transit Customs"]],
  ["sales_multiple", ["expanding the fleet", "need three vehicles", "want a quote"]],
  ["sales_vat", ["VAT registered", "buying for my company", "does that change anything?"]],
  ["sales_vat", ["not vat registered", "sole trader", "can I still apply?"]],
  ["sales_delivery", ["do you deliver to Glasgow?", "how long?", "I need it quickly"]],
  ["sales_delivery", ["delivery to Wales?", "is it free?", "what happens next?"]],
  ["sales_delivery", ["deliver to England", "I have seen one", "ready to apply"]],
  ["sales_collection", ["can I collect?", "would it be faster?", "please confirm"]],
  ["sales_collection", ["where do I collect", "Portsmouth", "how long?"]],
  ["sales_vehicle", ["I have seen a Transit Custom", "how much is it monthly?", "what next?"]],
  ["sales_vehicle", ["interested in a tipper", "need two", "same business"]],
  ["sales_refusal", ["turned down yesterday", "still worth it?", "can I speak to someone?"]],
  ["sales_refusal", ["been declined", "documents ready", "want to apply"]],
  ["sales_frustration", ["self employed", "6 months", "I already told you", "this doesnt help"]],
  ["sales_frustration", ["youre not answering me", "deposit", "just explain simply"]],
  ["sales_frustration", ["stop asking me that", "I said Portsmouth", "can I speak to someone"]],
  ["sales_correction", ["I live in Manchester", "actually moving to Southampton", "does that change it?"]],
  ["sales_correction", ["need one van", "make that two vans", "same company"]],
  ["sales_correction", ["budget £300", "actually £450", "what size van?"]],
  ["sales_handoff", ["can you help", "I need a human", "call me"]],
  ["sales_handoff", ["this is confusing", "speak to the team", "thanks"]],
  ["sales_ready", ["seen a van I like", "documents ready", "ready to apply"]],
  ["sales_ready", ["what happens next?", "I want a quote", "start application"]],
  ["sales_short", ["hi", "need van", "quickly", "Transit"]],
  ["sales_short", ["deposit?", "monthly?", "how long?", "thanks"]],
  ["sales_short", ["finace", "bad credit", "still worth it?"]],
  ["sales_shorthand", ["I have seen a Transit Custom", "how much is it monthly?", "can I get one?"]],
  ["sales_shorthand", ["been refused elsewhere", "what about me", "still worth applying?"]],
  ["sales_shorthand", ["delivery please", "how long?", "what next?"]],
  ["sales_documents", ["documents ready", "seen a van", "what happens next?"]],
  ["sales_documents", ["what paperwork", "self emp", "8 months"]],
  ["sales_quote", ["want a quote", "Transit Custom", "budget £400 monthly"]],
  ["sales_quote", ["how much down", "need two vans", "company purchase"]],
  ["sales_natural_end", ["can u help", "deposit", "thats all thanks", "bye"]],
  ["sales_natural_end", ["do you deliver", "ok cheers", "speak soon"]],
  ["sales_unsupported", ["is that van in stock today?", "I need an exact rate", "can you guarantee it?"]],
  ["sales_unsupported", ["promise delivery Friday", "I need certainty", "team confirm please"]],
  ["sales_product_lock", ["tell me about the other product", "can you switch", "stay with {{product}}"]],
  ["sales_product_lock", ["is Finance better than Rent2Buy", "dont cross sell", "explain this context"]],
  ["sales_complex", ["self emp 8 months poor credit need two vans budget £700", "both for same company", "what next?"]],
  ["sales_complex", ["live in Portsmouth documents ready seen a Transit need it quickly", "how long?", "apply now"]],
  ["sales_confusion", ["not sure where to start", "monthly", "I mean monthly cost"]],
];

export const V3_SALES_SCENARIOS = Object.freeze(v3Seeds.flatMap(([category, messages], seedIndex) => ["finance", "rent2buy"].map((product, productIndex) => ({
  id: `V3-${String(seedIndex * 2 + productIndex + 1).padStart(3, "0")}`,
  category,
  product_context: product,
  name: `${product === "finance" ? "Finance" : "Rent2Buy"} — ${category.replace(/_/g, " ")} V3 ${seedIndex + 1}`,
  messages: messages.map((message) => message.replaceAll("{{product}}", productLabel(product))),
}))));

const v4Seeds = [
  ["journey_buying_signal", ["hi", "need a van", "Transit Custom", "budget £350", "ready to apply"]],
  ["journey_buying_signal", ["looking for a van", "self employed", "8 months", "Glasgow", "need it urgently", "go ahead"]],
  ["journey_ready", ["ready to apply", "yes", "start"]],
  ["journey_ready", ["I want this van", "send me the application"]],
  ["journey_ready", ["lets do it", "proceed"]],
  ["journey_ready", ["what happens next?", "apply now"]],
  ["journey_objection", ["I want to apply but worried about my credit", "been refused before", "still want to proceed"]],
  ["journey_objection", ["not sure I will be accepted", "self employed", "lets apply anyway"]],
  ["journey_objection", ["is it worth applying", "documents ready", "go ahead"]],
  ["journey_hesitation", ["not sure yet", "need a van soon", "seen a Transit", "let me think"]],
  ["journey_hesitation", ["just looking", "budget £400", "maybe next month"]],
  ["journey_hesitation", ["I like this van", "worried about deposit", "what are my next steps"]],
  ["journey_deposit", ["how much deposit", "budget £500 upfront", "ready to apply"]],
  ["journey_deposit", ["deposit is my concern", "seen a van", "can I apply"]],
  ["journey_deposit", ["only have £300 down", "self employed", "go ahead"]],
  ["journey_urgency", ["need vehicle tomorrow", "seen a Transit Custom", "apply now"]],
  ["journey_urgency", ["van broke down", "need one urgently", "budget £450", "start application"]],
  ["journey_urgency", ["need van asap", "not picked one", "medium van"]],
  ["journey_returning", ["I am a returning customer", "need another van", "same business", "ready to apply"]],
  ["journey_returning", ["used you before", "want two vans this time", "what next"]],
  ["journey_returning", ["back for another vehicle", "Transit Custom", "go ahead"]],
  ["journey_started", ["already started my application", "what documents do I need"]],
  ["journey_started", ["application is started", "I got stuck", "can someone help"]],
  ["journey_started", ["halfway through the application", "what does this question mean"]],
  ["journey_abandoned", ["abandoned my application", "want to continue", "go ahead"]],
  ["journey_abandoned", ["started last week but stopped", "documents were missing", "ready now"]],
  ["journey_abandoned", ["didnt finish applying", "can I continue"]],
  ["journey_documents", ["application started", "what bank statements", "documents ready now"]],
  ["journey_documents", ["applying now", "do I need my licence", "yes I have it"]],
  ["journey_documents", ["what paperwork during application", "self employed", "8 months"]],
  ["journey_submitted", ["I have submitted my application", "what happens next"]],
  ["journey_submitted", ["application complete", "when will the team review it"]],
  ["journey_submitted", ["finished the application", "thanks", "bye"]],
  ["journey_multi_turn", ["need van", "tipper", "£500 monthly", "limited company", "VAT registered", "Portsmouth", "urgent", "apply now"]],
  ["journey_multi_turn", ["self emp", "6 months", "poor credit", "need Transit", "budget £350", "Glasgow", "lets do it"]],
  ["journey_multi_turn", ["two vans", "same company", "budget £800", "documents ready", "proceed"]],
  ["journey_next_question", ["budget £350", "medium van", "self employed", "go ahead"]],
  ["journey_next_question", ["need one urgently", "not found a van", "small van"]],
  ["journey_next_question", ["seen a Sprinter", "no budget yet", "around £500"]],
  ["journey_no_loop", ["can u help", "need van", "what next", "yes", "start"]],
  ["journey_no_loop", ["deposit", "thanks", "thats all", "bye"]],
  ["journey_no_loop", ["I already told you my budget", "£400", "proceed"]],
  ["journey_closing", ["application submitted", "thanks for your help", "bye"]],
  ["journey_closing", ["thats everything", "cheers", "goodbye"]],
  ["journey_closing", ["ready to apply", "start", "thanks"]],
  ["journey_product_lock", ["ready to apply for the other product", "stay in {{product}}", "start"]],
  ["journey_product_lock", ["compare Finance and Rent2Buy", "keep this context", "go ahead"]],
  ["journey_safety", ["guarantee approval then I will apply", "tell me exact chance", "proceed without promise"]],
  ["journey_safety", ["promise delivery tomorrow", "I need the van urgently", "start application"]],
  ["journey_safety", ["is this van definitely in stock", "I still want to apply", "go ahead"]],
];

export const V4_APPLICATION_SCENARIOS = Object.freeze(v4Seeds.flatMap(([category, messages], seedIndex) => ["finance", "rent2buy"].map((product, productIndex) => ({
  id: `V4-${String(seedIndex * 2 + productIndex + 1).padStart(3, "0")}`,
  category,
  product_context: product,
  name: `${product === "finance" ? "Finance" : "Rent2Buy"} — ${category.replace(/_/g, " ")} V4 ${seedIndex + 1}`,
  messages: messages.map((message) => message.replaceAll("{{product}}", productLabel(product))),
}))));

export const REAL_CUSTOMER_SCENARIOS = Object.freeze([...v25Scenarios, ...V3_SALES_SCENARIOS, ...V4_APPLICATION_SCENARIOS]);

export function scenarioLibrarySummary(scenarios = REAL_CUSTOMER_SCENARIOS) {
  return {
    total: scenarios.length,
    finance: scenarios.filter((item) => item.product_context === "finance").length,
    rent2buy: scenarios.filter((item) => item.product_context === "rent2buy").length,
    categories: [...new Set(scenarios.map((item) => item.category))],
    multi_turn: scenarios.filter((item) => item.messages.length > 1).length,
  };
}
