import { evaluateRent2BuyRule } from "./rent2BuyRules.js";

const clean = (value) => String(value || "").trim();
const normalize = (value) => clean(value).toLowerCase().replace(/[^a-z0-9£%\s]/g, " ").replace(/\s+/g, " ").trim();
const words = (value) => normalize(value).split(" ").filter(Boolean);
const sentenceList = (value) => clean(value).split(/(?<=[.!?])\s+|\n+/).map(clean).filter((item) => item.length >= 30);

export const PUBLISHING_SAFETY_MESSAGES = Object.freeze({
  duplicate_title: "Duplicate title or heading detected.", duplicate_sections: "Duplicate or repeated article sections detected.", raw_markdown: "Unprocessed formatting or raw markdown detected.", broken_link: "Broken or malformed link detected.", finance_claim: "Unverified financial or business claim requires confirmation.", stale_assessment: "Article content changed after assessment. Reanalyse before approval.", formatting: "Article formatting requires editorial correction.", repetition: "Excessive repetition or templated wording detected.", rent2buy_separation: "Rent2Buy content contains prohibited finance, delivery or trial wording, or is missing required collection-only facts.",
});
const SAFE_PROTOCOLS = new Set(["http:", "https:"]);
const PLACEHOLDERS = /\b(lorem ipsum|click here to add your own text|placeholder|insert (?:text|link|cta|answer)|tbc|todo)\b/i;
const FINANCE_CLAIMS = [/guaranteed\s+(?:approval|acceptance)/i,/approved?\s+(?:in|within)\s+\d+\s*(?:minutes?|hours?|days?)/i,/(?:from|only|just)?\s*£\s*\d[\d,]*(?:\.\d{1,2})?\s*(?:deposit|per month|monthly|repayment)/i,/\b\d+\s*(?:month|year)s?\s+(?:warranty|guarantee)/i,/\b\d[\d,]*\s*miles?\s+(?:warranty|guarantee)/i,/\b(?:panel|access)\s+(?:of|to)\s+\d+\s+lenders?\b/i,/\b(?:bad|poor|adverse)\s+credit\s+(?:accepted|welcome|approved)/i,/\bfree\s+(?:uk|nationwide)?\s*delivery\b/i,/\b(?:all|every)\s+(?:applications?|customers?)\s+(?:accepted|approved)\b/i,/\b(?:interest|apr)\s+(?:rate|from|of)\s*\d+(?:\.\d+)?%/i,/\b(?:you (?:only )?need|documents? required|must provide)\b/i];
function similarity(first, second) { const a = new Set(words(first).filter((word) => word.length > 2)); const b = new Set(words(second).filter((word) => word.length > 2)); if (!a.size || !b.size) return 0; return [...a].filter((word) => b.has(word)).length / Math.max(1, Math.min(a.size, b.size)); }
function markdownHeadings(markdown) { return clean(markdown).split(/\r?\n/).map((line,index)=>{const match=line.match(/^\s{0,3}(#{1,6})\s*(.*?)\s*#*\s*$/);return match?{level:match[1].length,text:clean(match[2]),index}:null;}).filter(Boolean); }
function sections(markdown) { const lines=clean(markdown).split(/\r?\n/); const output=[]; let current={heading:"Introduction",body:[]}; for(const line of lines){const heading=line.match(/^\s{0,3}#{1,6}\s+(.+?)\s*#*\s*$/);if(heading){if(current.body.join(" ").trim()||current.heading!=="Introduction")output.push(current);current={heading:clean(heading[1]),body:[]};}else current.body.push(line);} if(current.body.join(" ").trim()||current.heading!=="Introduction")output.push(current); return output.map((item)=>({...item,text:clean(item.body.join("\n"))})); }
function validDestination(value){const destination=clean(value);if(!destination)return false;if(destination.startsWith("/"))return !destination.startsWith("//")&&!/[\s<>]/.test(destination);try{const url=new URL(destination);return SAFE_PROTOCOLS.has(url.protocol)&&Boolean(url.hostname);}catch{return false;}}
function hasRawMarkdownInRenderedOutput(article){const outputs=[article.preview_text,article.rendered_preview,article.wix_content,article.wix_bound_output,article.content_html,article.exported_rich_content,article.rich_content_output].filter(Boolean).join("\n");if(!outputs)return false;return /\*\*[^*]+\*\*|\[[^\]]+\]\([^\s)]+\)|(?:^|\n)\s{0,3}#{1,6}\s+|```|(?:^|\n)\s*[-*+]\s+\S/m.test(outputs);}
function duplicateTitleCheck(article,headings){const title=normalize(article.title);if(!title)return false;const matching=headings.filter((heading)=>normalize(heading.text)===title);const counts=new Map();for(const heading of headings){const key=normalize(heading.text);if(key)counts.set(key,(counts.get(key)||0)+1);}return matching.some((heading)=>heading.level===1&&heading.index<=2)||[...counts.values()].some((count)=>count>1);}
function duplicateSectionsCheck(article,articleSections){const meaningful=articleSections.filter((section)=>words(section.text).length>=20);for(let i=0;i<meaningful.length;i+=1)for(let j=i+1;j<meaningful.length;j+=1)if(similarity(meaningful[i].text,meaningful[j].text)>=0.82)return true;const faqHeadings=articleSections.filter((section)=>/\bfaq|frequently asked questions\b/i.test(section.heading));if(faqHeadings.length>1)return true;const markdown=normalize(article.content_markdown);const faq=Array.isArray(article.faq_json)?article.faq_json:[];return faq.some((item)=>{const question=normalize(item?.question);const answer=normalize(item?.answer);return Boolean(question&&answer&&markdown.includes(question)&&markdown.includes(answer));});}
function linkCheck(article){const markdown=clean(article.content_markdown);const markdownLinks=[...markdown.matchAll(/\[([^\]]*)\]\(([^)]*)\)/g)];if(markdownLinks.some((match)=>!clean(match[1])||!validDestination(match[2])))return true;if(/\[[^\]]+\]\([^)]*$|\[[^\]]*$/.test(markdown))return true;const html=clean(article.content_html);const hrefs=[...html.matchAll(/<a\b[^>]*href=["']([^"']*)["'][^>]*>/gi)];if(hrefs.some((match)=>!validDestination(match[1])))return true;const ctas=Array.isArray(article.structured_ctas)?article.structured_ctas:[];if(ctas.some((cta)=>!clean(cta?.button_text)||!validDestination(cta?.destination)))return true;if(article.cta&&article.cta_destination!==undefined&&!validDestination(article.cta_destination))return true;return false;}
function confirmedKnowledgeText(context){const sections=context.businessKnowledge||context.business_sections||[];const sectionText=Array.isArray(sections)?sections.map((section)=>`${section?.content||""} ${(section?.entries||[]).map((entry)=>`${entry?.label||""} ${entry?.value||""}`).join(" ")}`).join(" "):clean(sections);return normalize(`${sectionText} ${(context.confirmedClaims||[]).join(" ")}`);}
function financeClaimCheck(article,context){const text=`${article.title||""}\n${article.excerpt||""}\n${article.content_markdown||""}\n${article.cta||""}`;const confirmed=confirmedKnowledgeText(context);const matches=FINANCE_CLAIMS.filter((pattern)=>pattern.test(text));if(!matches.length)return{blocked:false,requiresManual:false};const unsupported=matches.some((pattern)=>{const match=text.match(pattern)?.[0];return match&&!confirmed.includes(normalize(match));});return{blocked:unsupported,requiresManual:unsupported};}
function formattingCheck(article,headings,articleSections){const markdown=clean(article.content_markdown);if(words(markdown).length<180||PLACEHOLDERS.test(markdown))return true;if(headings.some((heading)=>!heading.text||words(heading.text).length>18||heading.text.length>140))return true;for(let i=0;i<headings.length-1;i+=1){const between=markdown.split(/\r?\n/).slice(headings[i].index+1,headings[i+1].index).join(" ");if(words(between).length<4)return true;}if(/(?:^|\n)\s*[-*+]\s*(?:\n|$)/m.test(markdown))return true;return articleSections.filter((section)=>/^(?:next step|apply now|contact us|ready to apply|what to do next)$/i.test(section.heading)).length>1;}
function repetitionCheck(article,articleSections){const text=`${article.title||""} ${article.content_markdown||""}`;const sentences=sentenceList(text);for(let i=0;i<sentences.length;i+=1)for(let j=i+1;j<sentences.length;j+=1)if(normalize(sentences[i])===normalize(sentences[j])||similarity(sentences[i],sentences[j])>=0.9)return true;const company=normalize(article.business_name||"Van Finance Company");const count=company?normalize(text).split(company).length-1:0;if(count>=Math.max(5,Math.ceil(words(text).length/180)))return true;const phrases=new Map();const tokens=words(text);for(let size=5;size<=7;size+=1)for(let i=0;i<=tokens.length-size;i+=1){const phrase=tokens.slice(i,i+size).join(" ");phrases.set(phrase,(phrases.get(phrase)||0)+1);}if([...phrases.values()].some((value)=>value>=4))return true;return articleSections.some((section,index)=>articleSections.slice(index+1).some((other)=>words(section.text).length>=35&&similarity(section.text,other.text)>=0.78));}
function assessmentIsStale(article,assessment,options){if(options.ignoreAssessmentFreshness===true)return false;if(options.stale===true)return true;if(!assessment)return true;const currentHash=options.currentContentHash||article.content_hash;const assessedHash=assessment.content_hash||assessment.article_content_hash;if(currentHash&&assessedHash)return currentHash!==assessedHash;const changedAt=new Date(article.updated_at||0).getTime();const assessedAt=new Date(assessment.created_at||assessment.updated_at||0).getTime();return Boolean(changedAt&&assessedAt&&changedAt>assessedAt);}

export function evaluatePublishingSafety(article={},options={}){const assessment=options.assessment||article.assessment||null;const headings=markdownHeadings(article.content_markdown);const articleSections=sections(article.content_markdown);const duplicateTitle=duplicateTitleCheck(article,headings);const duplicateSections=duplicateSectionsCheck(article,articleSections);const rawMarkdown=hasRawMarkdownInRenderedOutput(article)||Boolean(options.rawMarkdownVisible);const brokenLinks=linkCheck({...article,structured_ctas:options.structuredCtas||article.structured_ctas});const finance=financeClaimCheck(article,options);const stale=assessmentIsStale(article,assessment,options);const formatting=formattingCheck(article,headings,articleSections);const repetition=repetitionCheck(article,articleSections);const rent2buy=evaluateRent2BuyRule(article,{...options,assessment});const checks={formatting:formatting?"blocked":"passed",duplicate_content:duplicateTitle||duplicateSections?"blocked":"passed",links:brokenLinks?"blocked":"passed",finance_claims:finance.blocked?"warning":"passed",assessment_freshness:stale?"blocked":"passed",repetition:repetition?"blocked":"passed",rent2buy_separation:rent2buy.passed?"passed":"blocked"};const reasons=[];if(duplicateTitle)reasons.push(PUBLISHING_SAFETY_MESSAGES.duplicate_title);if(duplicateSections)reasons.push(PUBLISHING_SAFETY_MESSAGES.duplicate_sections);if(rawMarkdown)reasons.push(PUBLISHING_SAFETY_MESSAGES.raw_markdown);if(brokenLinks)reasons.push(PUBLISHING_SAFETY_MESSAGES.broken_link);if(finance.blocked)reasons.push(PUBLISHING_SAFETY_MESSAGES.finance_claim);if(stale)reasons.push(PUBLISHING_SAFETY_MESSAGES.stale_assessment);if(formatting)reasons.push(PUBLISHING_SAFETY_MESSAGES.formatting);if(repetition)reasons.push(PUBLISHING_SAFETY_MESSAGES.repetition);if(!rent2buy.passed)reasons.push(PUBLISHING_SAFETY_MESSAGES.rent2buy_separation);return{hard_blocked:reasons.length>0,hard_block_reasons:[...new Set(reasons)],formatting_hygiene_passed:!formatting&&!rawMarkdown,requires_manual_claim_review:finance.requiresManual,recommended_action:reasons.length?"Hold — corrections required":"Publish",checks,rent2buy_rule:rent2buy};}
export function assertPublishingSafe(article,options={}){const result=evaluatePublishingSafety(article,options);if(result.hard_blocked){const error=new Error(result.hard_block_reasons.join(" "));error.code="KNOWLEDGE_HARD_BLOCK";error.safety=result;throw error;}return result;}
export function auditPublishedArticles({articles=[],assessments=[],...options}={}){const latest=new Map();[...assessments].sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0)).forEach((assessment)=>{if(!latest.has(assessment.article_id))latest.set(assessment.article_id,assessment);});return articles.filter((article)=>["approved","exported"].includes(article.status)).map((article)=>({article,safety:evaluatePublishingSafety(article,{...options,assessment:latest.get(article.id)})})).filter((item)=>item.safety.hard_blocked||item.safety.requires_manual_claim_review);}
