from pathlib import Path

COMMIT = "Reorder AI Visibility and paginate article results"


def replace_once(path, old, new):
    file = Path(path)
    text = file.read_text(encoding="utf-8")
    if old not in text:
        raise SystemExit(f"marker not found in {path}: {old[:120]!r}")
    file.write_text(text.replace(old, new, 1), encoding="utf-8")


# Keep the live provider panel compact and collapse manual-only providers by default.
path = Path("components/AIVisibilityLiveConnections.jsx")
text = path.read_text(encoding="utf-8")
text = text.replace(
    '      <div className="notice">Google Search Console is checked automatically when requested. ChatGPT, Gemini, Perplexity and Google AI Overviews require a manual public search and verified evidence.</div>\n      <details className="notice"><summary>How to run a manual check</summary><ol><li>Select an article.</li><li>Copy the suggested query.</li><li>Open the public provider.</li><li>Run the search in a clean session.</li><li>Record Detected, Not detected or Inconclusive.</li><li>Save only what you actually observed.</li></ol></details>\n      <div className="card-grid">\n        {MANUAL_PROVIDERS.map((provider) => {\n          const latest = latestProviderResult((data?.results || []).filter((result) => publishedIds.has(result.article_id)), provider);\n          return <article className="panel panel--nested" style={{ boxShadow: "none" }} key={provider}><div className="panel__header"><div><strong>{PROVIDER_LABELS[provider]}</strong><p>{MANUAL_PROVIDER_EXPLANATION}</p></div><span className="visibility-status is-neutral">{manualProviderStatus(latest)}</span></div><small>Last checked: {latest?.checked_at ? new Date(latest.checked_at).toLocaleString("en-GB") : "Never"}</small>{latest ? <div className="card-actions"><button className="button button--ghost" type="button" onClick={() => setManualProvider(provider)}>View Evidence</button></div> : null}<button className="button button--primary" type="button" onClick={() => setManualProvider(provider)}>Run Manual Check</button></article>;\n        })}\n      </div>\n      {manualProvider ? <ManualCheckWorkflow provider={manualProvider} data={data} onClose={() => setManualProvider("")} onSaved={async () => { await refresh(); window.dispatchEvent(new CustomEvent("ai-visibility-live-data-updated")); }} /> : null}',
    '      <details className="panel panel--nested" style={{ boxShadow: "none" }} data-manual-ai-checks>\n        <summary><strong>Manual AI checks</strong> · 4 manual providers available</summary>\n        <div className="operations-drawer__body">\n          <div className="notice">Google Search Console is checked automatically when requested. ChatGPT, Gemini, Perplexity and Google AI Overviews require a manual public search and verified evidence.</div>\n          <details className="notice"><summary>How to run a manual check</summary><ol><li>Select an article.</li><li>Copy the suggested query.</li><li>Open the public provider.</li><li>Run the search in a clean session.</li><li>Record Detected, Not detected or Inconclusive.</li><li>Save only what you actually observed.</li></ol></details>\n          <div className="card-grid">\n            {MANUAL_PROVIDERS.map((provider) => {\n              const latest = latestProviderResult((data?.results || []).filter((result) => publishedIds.has(result.article_id)), provider);\n              return <article className="panel panel--nested" style={{ boxShadow: "none" }} key={provider}><div className="panel__header"><div><strong>{PROVIDER_LABELS[provider]}</strong><p>{MANUAL_PROVIDER_EXPLANATION}</p></div><span className="visibility-status is-neutral">{manualProviderStatus(latest)}</span></div><small>Last checked: {latest?.checked_at ? new Date(latest.checked_at).toLocaleString("en-GB") : "Never"}</small>{latest ? <div className="card-actions"><button className="button button--ghost" type="button" onClick={() => setManualProvider(provider)}>View Evidence</button></div> : null}<button className="button button--primary" type="button" onClick={() => setManualProvider(provider)}>Run Manual Check</button></article>;\n            })}\n          </div>\n          {manualProvider ? <ManualCheckWorkflow provider={manualProvider} data={data} onClose={() => setManualProvider("")} onSaved={async () => { await refresh(); setManualProvider(""); window.dispatchEvent(new CustomEvent("ai-visibility-live-data-updated")); }} /> : null}\n        </div>\n      </details>'
)
text = text.replace(
    'const stack = heading.closest(".page-stack"); if (stack && !stack.querySelector("[data-ai-visibility-live-host]")) { const host = document.createElement("div"); host.dataset.aiVisibilityLiveHost = "true"; heading.closest(".hero-panel")?.insertAdjacentElement("afterend", host); mountRoot("centre", host, <LiveConnectionsPanel />); }',
    'const stack = heading.closest(".page-stack"); const anchor = stack?.querySelector("[data-ai-visibility-live-anchor]"); if (anchor && !stack.querySelector("[data-ai-visibility-live-host]")) { const host = document.createElement("div"); host.dataset.aiVisibilityLiveHost = "true"; anchor.insertAdjacentElement("afterend", host); mountRoot("centre", host, <LiveConnectionsPanel />); }'
)
path.write_text(text, encoding="utf-8")

# Reorder the page and add client-side pagination without touching evidence calculations.
path = Path("pages/AIVisibilityPage.jsx")
text = path.read_text(encoding="utf-8")
text = text.replace('const GOOGLE_RESULT_OPTIONS = ["indexed", "not_indexed"];', 'const GOOGLE_RESULT_OPTIONS = ["indexed", "not_indexed"];\nconst ARTICLE_PAGE_SIZES = [10, 25, 50, 100];')
text = text.replace(
    '  const [message, setMessage] = useState("");',
    '  const [message, setMessage] = useState("");\n  const [articlePage, setArticlePage] = useState(1);\n  const [articlePageSize, setArticlePageSize] = useState(25);\n  const [articlesOpen, setArticlesOpen] = useState(() => { try { return sessionStorage.getItem("aiVisibilityArticlesOpen") === "true"; } catch { return false; } });'
)
text = text.replace(
    '  const selected = summary?.articles.find((item) => item.article.id === selectedId);\n  const applyMetric = (metric) => setFilters((current) => filtersForMetric(metric, current));',
    '  const articlePageCount = Math.max(1, Math.ceil(rows.length / articlePageSize));\n  const safeArticlePage = Math.min(articlePage, articlePageCount);\n  const pageStart = rows.length ? (safeArticlePage - 1) * articlePageSize : 0;\n  const pageRows = rows.slice(pageStart, pageStart + articlePageSize);\n  const pageEnd = Math.min(pageStart + articlePageSize, rows.length);\n  const selected = summary?.articles.find((item) => item.article.id === selectedId);\n  useEffect(() => setArticlePage(1), [filters.search, filters.provider, filters.status, filters.from, filters.to, filters.sort, articlePageSize]);\n  useEffect(() => { if (articlePage > articlePageCount) setArticlePage(articlePageCount); }, [articlePage, articlePageCount]);\n  const applyMetric = (metric) => { setFilters((current) => filtersForMetric(metric, current)); setArticlePage(1); setArticlesOpen(true); try { sessionStorage.setItem("aiVisibilityArticlesOpen", "true"); } catch {} };'
)
text = text.replace(
    '      {summary ? <SummaryCards summary={summary} onFilter={applyMetric} /> : null}\n      {data ? <ProviderConnections providers={data.provider_connections} /> : null}\n      {data ? <PublicationForm articles={data.articles} busy={busy} onSave={(articleId, publication) => act(() => saveVisibilityPublication(articleId, publication), "Verified Wix publication saved.")} /> : null}',
    '      {summary ? <SummaryCards summary={summary} onFilter={applyMetric} /> : null}\n      <div data-ai-visibility-live-anchor />'
)
text = text.replace(
    '          <section className="panel">\n            <div className="panel__header">\n              <div><h3>Published article results</h3><p>Visibility rate excludes unchecked articles and provider errors.</p></div>',
    '          <details className="panel" open={articlesOpen} onToggle={(event) => { const open = event.currentTarget.open; setArticlesOpen(open); try { sessionStorage.setItem("aiVisibilityArticlesOpen", String(open)); } catch {} }} data-ai-visibility-article-results>\n            <summary><strong>Published article results</strong> · {summary.published_pages} published pages · {summary.articles.filter((item) => item.checked_successfully).length} checked</summary>\n            <div className="operations-drawer__body">\n            <div className="panel__header">\n              <div><h3>Published article results</h3><p>Visibility rate excludes unchecked articles and provider errors.</p></div>'
)
text = text.replace('{rows.map((item) => (', '{pageRows.map((item) => (')
text = text.replace(
    '            </div>\n          </section>\n          <section className="knowledge-three-column">',
    '            </div>\n            <div className="panel__header" style={{ marginTop: 14, alignItems: "end" }}>\n              <div><strong>Showing {rows.length ? pageStart + 1 : 0}–{pageEnd} of {rows.length}</strong></div>\n              <label className="field" style={{ minWidth: 120 }}><span className="field__label">Rows per page</span><select className="field__input" value={articlePageSize} onChange={(event) => setArticlePageSize(Number(event.target.value))}>{ARTICLE_PAGE_SIZES.map((size) => <option value={size} key={size}>{size}</option>)}</select></label>\n              <div className="card-actions" aria-label="Article result pages">\n                <button className="button button--ghost" type="button" aria-label="Previous article results page" disabled={safeArticlePage <= 1} onClick={() => setArticlePage((page) => Math.max(1, page - 1))}>Previous</button>\n                {Array.from({ length: articlePageCount }, (_, index) => index + 1).filter((page) => articlePageCount <= 7 || page === 1 || page === articlePageCount || Math.abs(page - safeArticlePage) <= 1).map((page) => <button className="button button--ghost" type="button" aria-label={`Article results page ${page}`} aria-current={page === safeArticlePage ? "page" : undefined} key={page} onClick={() => setArticlePage(page)}>{page}</button>)}\n                <button className="button button--ghost" type="button" aria-label="Next article results page" disabled={safeArticlePage >= articlePageCount} onClick={() => setArticlePage((page) => Math.min(articlePageCount, page + 1))}>Next</button>\n              </div>\n            </div>\n            </div>\n          </details>\n          <section className="knowledge-three-column">'
)
text = text.replace(
    '          </section>\n        </>\n      ) : null}\n    </div>',
    '          </section>\n          {data ? <PublicationForm articles={data.articles} busy={busy} onSave={(articleId, publication) => act(() => saveVisibilityPublication(articleId, publication), "Verified Wix publication saved.")} /> : null}\n        </>\n      ) : null}\n    </div>'
)
path.write_text(text, encoding="utf-8")

# Focused source-level tests for layout/pagination only.
Path("tests/ai-visibility-layout-pagination.test.js").write_text('''import test from "node:test";\nimport assert from "node:assert/strict";\nimport { readFile } from "node:fs/promises";\n\nconst read = (path) => readFile(new URL(path, import.meta.url), "utf8");\n\ntest("statistics render before the live controls and manual providers", async () => {\n  const page = await read("../pages/AIVisibilityPage.jsx");\n  assert.ok(page.indexOf("<SummaryCards") < page.indexOf("data-ai-visibility-live-anchor"));\n});\n\ntest("manual AI checks are collapsed by default and workflow closes after save", async () => {\n  const component = await read("../components/AIVisibilityLiveConnections.jsx");\n  assert.match(component, /<details[^>]*data-manual-ai-checks/);\n  assert.match(component, /Manual AI checks/);\n  assert.match(component, /4 manual providers available/);\n  assert.match(component, /setManualProvider\(""\)/);\n  assert.match(component, /How to run a manual check/);\n});\n\ntest("published article results use client-side pagination with required page sizes", async () => {\n  const page = await read("../pages/AIVisibilityPage.jsx");\n  assert.match(page, /ARTICLE_PAGE_SIZES = \[10, 25, 50, 100\]/);\n  assert.match(page, /useState\(25\)/);\n  assert.match(page, /pageRows = rows\.slice/);\n  assert.match(page, /Showing \{rows\.length \? pageStart \+ 1 : 0\}–\{pageEnd\} of \{rows\.length\}/);\n  assert.match(page, /Previous article results page/);\n  assert.match(page, /Next article results page/);\n  assert.match(page, /aria-current=\{page === safeArticlePage \? "page"/);\n  assert.match(page, /View Evidence/);\n});\n\ntest("filter and sort changes reset pagination", async () => {\n  const page = await read("../pages/AIVisibilityPage.jsx");\n  assert.match(page, /useEffect\(\(\) => setArticlePage\(1\), \[filters\.search, filters\.provider, filters\.status, filters\.from, filters\.to, filters\.sort, articlePageSize\]\)/);\n});\n\ntest("Google and Wix behaviour remain explicit and unchanged", async () => {\n  const component = await read("../components/AIVisibilityLiveConnections.jsx");\n  assert.match(component, /Check Google for Published Pages/);\n  assert.match(component, /Sync Live Wix Articles/);\n  assert.doesNotMatch(component, /useEffect\([^]*checkGoogleForPublishedPages/);\n  assert.doesNotMatch(component, /publishLive|livePublish|puppeteer|playwright/);\n});\n''', encoding="utf-8")
