-- Knowledge Hub AI Visibility Centre.
-- Additive, evidence-only monitoring. No rankings or detections are generated by this migration.

alter table public.knowledge_articles
  add column if not exists wix_item_id text,
  add column if not exists wix_collection_id text,
  add column if not exists live_wix_url text,
  add column if not exists published_at timestamptz,
  add column if not exists last_wix_sync_at timestamptz,
  add column if not exists wix_sync_status text not null default 'not_configured'
    check (wix_sync_status in ('not_configured', 'pending', 'synced', 'live', 'error')),
  add column if not exists publication_verified_at timestamptz,
  add column if not exists publication_verification_notes text not null default '';

create table if not exists public.knowledge_visibility_settings (
  settings_key text primary key default 'default',
  attention_days integer not null default 30 check (attention_days between 1 and 365),
  maximum_active_prompts_per_article integer not null default 8
    check (maximum_active_prompts_per_article between 1 and 25),
  updated_at timestamptz not null default now()
);

insert into public.knowledge_visibility_settings (settings_key)
values ('default')
on conflict (settings_key) do nothing;

create table if not exists public.knowledge_visibility_provider_connections (
  provider text primary key check (
    provider in (
      'google_search_console',
      'chatgpt',
      'gemini',
      'perplexity',
      'google_ai_overviews'
    )
  ),
  connection_status text not null default 'configuration_required'
    check (connection_status in ('connected', 'not_connected', 'configuration_required')),
  configuration_summary text not null default '',
  connection_metadata jsonb not null default '{}'::jsonb
    check (jsonb_typeof(connection_metadata) = 'object'),
  last_successful_check_at timestamptz,
  last_error_at timestamptz,
  last_error text not null default '',
  updated_at timestamptz not null default now()
);

insert into public.knowledge_visibility_provider_connections
  (provider, connection_status, configuration_summary)
values
  ('google_search_console', 'configuration_required', 'Google Search Console adapter requires verified API credentials and property access.'),
  ('chatgpt', 'configuration_required', 'No supported public ChatGPT visibility evidence provider is configured.'),
  ('gemini', 'configuration_required', 'No supported public Gemini visibility evidence provider is configured.'),
  ('perplexity', 'configuration_required', 'No supported public Perplexity visibility evidence provider is configured.'),
  ('google_ai_overviews', 'configuration_required', 'No supported Google AI Overviews evidence provider is configured.')
on conflict (provider) do nothing;

create table if not exists public.knowledge_visibility_prompts (
  id uuid primary key default gen_random_uuid(),
  article_id uuid not null references public.knowledge_articles(id) on delete cascade,
  prompt_text text not null,
  prompt_source text not null default 'manual'
    check (prompt_source in ('article_title', 'search_intent', 'faq', 'customer_question', 'business_brain', 'manual')),
  prompt_fingerprint text not null,
  active boolean not null default true,
  created_by text not null default 'administrator',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (article_id, prompt_fingerprint)
);

create table if not exists public.knowledge_visibility_results (
  id uuid primary key default gen_random_uuid(),
  article_id uuid not null references public.knowledge_articles(id) on delete cascade,
  prompt_id uuid references public.knowledge_visibility_prompts(id) on delete set null,
  provider text not null check (
    provider in (
      'google_search_console',
      'chatgpt',
      'gemini',
      'perplexity',
      'google_ai_overviews'
    )
  ),
  checked_at timestamptz not null,
  result_status text not null check (
    result_status in (
      'not_checked',
      'checking',
      'indexed',
      'not_indexed',
      'detected',
      'mentioned',
      'cited',
      'not_detected',
      'error'
    )
  ),
  source_url text,
  evidence_excerpt text not null default '',
  structured_evidence jsonb not null default '{}'::jsonb
    check (jsonb_typeof(structured_evidence) = 'object'),
  confidence smallint check (confidence between 0 and 100),
  response_metadata jsonb not null default '{}'::jsonb
    check (jsonb_typeof(response_metadata) = 'object'),
  error_details text not null default '',
  notes text not null default '',
  verification_method text not null default 'provider'
    check (verification_method in ('provider', 'manual')),
  manually_verified boolean not null default false,
  supersedes_result_id uuid references public.knowledge_visibility_results(id) on delete set null,
  created_at timestamptz not null default now(),
  check (
    result_status not in ('detected', 'mentioned', 'cited')
    or length(trim(evidence_excerpt)) > 0
    or structured_evidence <> '{}'::jsonb
  ),
  check (
    verification_method = 'manual' and manually_verified
    or verification_method = 'provider' and not manually_verified
  )
);

create table if not exists public.knowledge_visibility_audit_events (
  id uuid primary key default gen_random_uuid(),
  article_id uuid references public.knowledge_articles(id) on delete set null,
  prompt_id uuid references public.knowledge_visibility_prompts(id) on delete set null,
  result_id uuid references public.knowledge_visibility_results(id) on delete set null,
  provider text,
  action text not null check (
    action in (
      'provider_check_started',
      'provider_check_completed',
      'provider_check_failed',
      'manual_result_recorded',
      'result_superseded',
      'prompt_created',
      'prompt_updated',
      'prompt_disabled',
      'prompts_derived',
      'connection_changed',
      'publication_updated',
      'dashboard_calculated'
    )
  ),
  reason text not null default '',
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists knowledge_articles_wix_publication_idx
  on public.knowledge_articles (published_at desc)
  where live_wix_url is not null and publication_verified_at is not null;

create index if not exists knowledge_visibility_prompts_article_idx
  on public.knowledge_visibility_prompts (article_id, active, updated_at desc);

create index if not exists knowledge_visibility_results_article_idx
  on public.knowledge_visibility_results (article_id, checked_at desc, provider);

create index if not exists knowledge_visibility_results_provider_idx
  on public.knowledge_visibility_results (provider, result_status, checked_at desc);

create index if not exists knowledge_visibility_audit_idx
  on public.knowledge_visibility_audit_events (created_at desc, action, article_id);

alter table public.knowledge_visibility_settings enable row level security;
alter table public.knowledge_visibility_provider_connections enable row level security;
alter table public.knowledge_visibility_prompts enable row level security;
alter table public.knowledge_visibility_results enable row level security;
alter table public.knowledge_visibility_audit_events enable row level security;

-- No browser policies. Protected Marketing CRM API routes use the service role.
