create table if not exists public.facebook_group_state (
  group_key text primary key,
  group_url text,
  group_name text,
  finance boolean not null default true,
  rent2buy boolean not null default true,
  state jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists facebook_group_state_updated_at_idx
  on public.facebook_group_state (updated_at desc);

create index if not exists facebook_group_state_products_idx
  on public.facebook_group_state (finance, rent2buy);

alter table public.facebook_group_state enable row level security;

revoke all on table public.facebook_group_state from anon, authenticated;
grant select, insert, update on table public.facebook_group_state to service_role;


create table if not exists public.facebook_group_state_backups (
  id bigint generated by default as identity primary key,
  reason text not null default 'automatic',
  group_count integer not null default 0,
  snapshot jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists facebook_group_state_backups_created_at_idx
  on public.facebook_group_state_backups (created_at desc);

alter table public.facebook_group_state_backups enable row level security;

revoke all on table public.facebook_group_state_backups from anon, authenticated;
grant select, insert on table public.facebook_group_state_backups to service_role;
