create table if not exists public.site_analytics_sessions (
  session_id text primary key,
  visitor_id text not null,
  started_at timestamptz not null,
  last_activity_at timestamptz not null,
  ended_at timestamptz,
  landing_path text not null,
  last_path text not null,
  page_view_count integer not null default 0 check (page_view_count >= 0),
  meaningful_event_count integer not null default 0 check (meaningful_event_count >= 0),
  referrer text,
  source text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  device_category text,
  browser_category text,
  viewport_width integer check (viewport_width is null or viewport_width between 0 and 10000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (char_length(session_id) between 16 and 100),
  check (char_length(visitor_id) between 16 and 100)
);

create table if not exists public.site_analytics_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  session_id text not null references public.site_analytics_sessions(session_id) on delete cascade,
  visitor_id text not null,
  event_name text not null check (event_name in (
    'session_start',
    'session_activity',
    'session_end',
    'page_view',
    'engagement',
    'vehicle_view',
    'finance_application_reached',
    'finance_application_completed',
    'rent2buy_postcode_gate_reached',
    'rent2buy_postcode_pass',
    'rent2buy_postcode_fail',
    'rent2buy_full_application_opened',
    'rent2buy_application_completed',
    'part_exchange_started',
    'part_exchange_completed'
  )),
  occurred_at timestamptz not null,
  received_at timestamptz not null default now(),
  path text not null,
  page_url text not null,
  vehicle_registration text,
  metadata jsonb not null default '{}'::jsonb,
  check (char_length(session_id) between 16 and 100),
  check (char_length(visitor_id) between 16 and 100),
  check (char_length(path) between 1 and 500),
  check (char_length(page_url) between 1 and 800),
  check (vehicle_registration is null or char_length(vehicle_registration) between 2 and 16),
  check (jsonb_typeof(metadata) = 'object')
);

alter table public.site_analytics_sessions enable row level security;
alter table public.site_analytics_events enable row level security;

revoke all on table public.site_analytics_sessions from anon, authenticated;
revoke all on table public.site_analytics_events from anon, authenticated;
revoke all on sequence public.site_analytics_events_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.site_analytics_sessions to service_role;
grant select, insert, update, delete on table public.site_analytics_events to service_role;
grant usage, select on sequence public.site_analytics_events_id_seq to service_role;

create index if not exists site_analytics_sessions_started_at_idx
  on public.site_analytics_sessions (started_at desc);
create index if not exists site_analytics_sessions_visitor_started_idx
  on public.site_analytics_sessions (visitor_id, started_at desc);
create index if not exists site_analytics_events_occurred_at_idx
  on public.site_analytics_events (occurred_at desc);
create index if not exists site_analytics_events_name_occurred_idx
  on public.site_analytics_events (event_name, occurred_at desc);
create index if not exists site_analytics_events_session_occurred_idx
  on public.site_analytics_events (session_id, occurred_at asc);
create index if not exists site_analytics_events_vehicle_occurred_idx
  on public.site_analytics_events (vehicle_registration, occurred_at desc)
  where vehicle_registration is not null;

create or replace function public.ingest_site_analytics_event(
  p_event_id uuid,
  p_session_id text,
  p_visitor_id text,
  p_event_name text,
  p_occurred_at timestamptz,
  p_path text,
  p_page_url text,
  p_landing_path text,
  p_referrer text default null,
  p_source text default null,
  p_utm_source text default null,
  p_utm_medium text default null,
  p_utm_campaign text default null,
  p_device_category text default null,
  p_browser_category text default null,
  p_viewport_width integer default null,
  p_vehicle_registration text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  inserted_rows integer := 0;
  is_page_view integer := case when p_event_name = 'page_view' then 1 else 0 end;
  is_meaningful integer := case when p_event_name in (
    'engagement', 'vehicle_view', 'finance_application_reached',
    'finance_application_completed', 'rent2buy_postcode_gate_reached',
    'rent2buy_postcode_pass', 'rent2buy_postcode_fail',
    'rent2buy_full_application_opened', 'rent2buy_application_completed',
    'part_exchange_started', 'part_exchange_completed'
  ) then 1 else 0 end;
begin
  insert into public.site_analytics_sessions (
    session_id, visitor_id, started_at, last_activity_at, ended_at,
    landing_path, last_path, page_view_count, meaningful_event_count,
    referrer, source, utm_source, utm_medium, utm_campaign,
    device_category, browser_category, viewport_width
  ) values (
    p_session_id, p_visitor_id, p_occurred_at, p_occurred_at,
    case when p_event_name = 'session_end' then p_occurred_at else null end,
    p_landing_path, p_path, 0, 0,
    p_referrer, p_source, p_utm_source, p_utm_medium, p_utm_campaign,
    p_device_category, p_browser_category, p_viewport_width
  )
  on conflict (session_id) do nothing;

  insert into public.site_analytics_events (
    event_id, session_id, visitor_id, event_name, occurred_at,
    path, page_url, vehicle_registration, metadata
  ) values (
    p_event_id, p_session_id, p_visitor_id, p_event_name, p_occurred_at,
    p_path, p_page_url, p_vehicle_registration, coalesce(p_metadata, '{}'::jsonb)
  )
  on conflict (event_id) do nothing;

  get diagnostics inserted_rows = row_count;
  if inserted_rows = 0 then
    delete from public.site_analytics_sessions session_row
    where session_row.session_id = p_session_id
      and not exists (
        select 1 from public.site_analytics_events event_row
        where event_row.session_id = session_row.session_id
      );
    return false;
  end if;

  update public.site_analytics_sessions
  set
    visitor_id = p_visitor_id,
    started_at = least(started_at, p_occurred_at),
    last_path = case when p_occurred_at >= last_activity_at then p_path else last_path end,
    last_activity_at = greatest(last_activity_at, p_occurred_at),
    ended_at = case when p_event_name = 'session_end' then greatest(coalesce(ended_at, p_occurred_at), p_occurred_at) else ended_at end,
    page_view_count = page_view_count + is_page_view,
    meaningful_event_count = meaningful_event_count + is_meaningful,
    source = coalesce(source, p_source),
    utm_source = coalesce(utm_source, p_utm_source),
    utm_medium = coalesce(utm_medium, p_utm_medium),
    utm_campaign = coalesce(utm_campaign, p_utm_campaign),
    referrer = coalesce(referrer, p_referrer),
    device_category = coalesce(device_category, p_device_category),
    browser_category = coalesce(browser_category, p_browser_category),
    viewport_width = coalesce(viewport_width, p_viewport_width),
    updated_at = now()
  where session_id = p_session_id;

  return true;
end;
$$;

revoke all on function public.ingest_site_analytics_event(
  uuid, text, text, text, timestamptz, text, text, text,
  text, text, text, text, text, text, text, integer, text, jsonb
) from public, anon, authenticated;

grant execute on function public.ingest_site_analytics_event(
  uuid, text, text, text, timestamptz, text, text, text,
  text, text, text, text, text, text, text, integer, text, jsonb
) to service_role;
