import { createClient } from "@supabase/supabase-js";

const WIX_FINANCE_CMS_ENDPOINT = "https://www.vanfinancecompany.co.uk/_functions/marketingVanFinanceImages";
const SUPPORTED_MAKES = new Set(["Ford","Mercedes-Benz","Renault","Volkswagen","Fiat","Peugeot","Citroen","Vauxhall","Nissan","Iveco","MAN","MAXUS","Dacia","DFSK","Hyundai","Suzuki","Mitsubishi","Kia","Toyota","LDV","Isuzu"]);
const MODEL_RULES = {"Mercedes-Benz":["Sprinter","Vito","Citan"],Renault:["Trafic","Master","Kangoo"],Volkswagen:["Transporter","Caddy","Crafter","Amarok"],Fiat:["Ducato","Doblo","Talento","Scudo"],Peugeot:["Partner","Expert","Boxer"],Citroen:["Berlingo","Dispatch","Relay"],Vauxhall:["Vivaro","Combo","Movano"],Nissan:["Primastar","NV200","NV300","NV400","Interstar","Navara"],Iveco:["Daily"],MAN:["TGE"],MAXUS:["eDeliver 9","eDeliver 3","Deliver 9","Deliver 3"],Toyota:["Proace","Hilux"],Isuzu:["D-Max"],Mitsubishi:["L200"],Hyundai:["iLoad","H350"],LDV:["V80"]};
function getSupabase(){const url=process.env.SUPABASE_URL||process.env.VITE_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.VITE_SUPABASE_ANON_KEY;if(!url||!key)throw new Error("Missing Supabase environment variables.");return createClient(url,key,{auth:{persistSession:false}})}
function clean(v){return String(v??"").replace(/\s+/g," ").trim()}
function registrationKey(v){return clean(v).toUpperCase().replace(/[^A-Z0-9]/g,"")}
function extractRegistration(...values){const text=values.map(clean).join(" ").toUpperCase();const m=text.match(/\b([A-Z]{2}[0-9]{2}\s?[A-Z]{3}|[A-Z][0-9]{1,3}\s?[A-Z]{3}|[A-Z]{3}\s?[0-9]{1,3}[A-Z]|[0-9]{1,4}\s?[A-Z]{1,3})\b/);return m?registrationKey(m[1]):""}
function labelledSpecValue(spec,label){const lines=String(spec||"").replace(/\r/g,"\n").split(/\n+/).map(x=>x.trim()).filter(Boolean);const wanted=String(label||"").toUpperCase();const line=lines.find(x=>x.toUpperCase().startsWith(`${wanted}:`));if(line)return line.slice(line.indexOf(":")+1).trim();const flat=String(spec||"").replace(/\s+/g," ");const m=flat.match(new RegExp(`${wanted}\\s*:\\s*([^_]{1,40})`,"i"));return m?clean(m[1]):""}
function parseYear(spec,reg,...fallbacks){const labelled=labelledSpecValue(spec,"YEAR");const ym=labelled.match(/\b(20[0-3][0-9])\b/);if(ym)return ym[1];const t=fallbacks.map(clean).join(" ");const e=t.match(/\b(20[0-3][0-9])\b/);if(e)return e[1];const age=registrationKey(reg).match(/^[A-Z]{2}([0-9]{2})[A-Z]{3}$/);if(!age)return "";const n=Number(age[1]);return n>=50?String(2000+n-50):String(2000+n)}
function parseMileage(spec,...fallbacks){const labelled=labelledSpecValue(spec,"MILEAGE");const digits=labelled.replace(/[^0-9]/g,"");if(digits)return digits;const text=fallbacks.map(clean).join(" ");const m=text.match(/\b([0-9]{1,3}(?:,[0-9]{3})+|[0-9]{4,6})\s*(?:MILES?|MLS)\b/i);return m?m[1].replace(/,/g,""):""}
function parseMoney(v){const m=String(v||"").replace(/,/g,"").match(/\d+(?:\.\d+)?/);return m?String(Math.round(Number(m[0]))):""}
function detectMake(text){const rules=[["Mercedes-Benz",/\b(mercedes|mercedes-benz|benz)\b/i],["Volkswagen",/\b(volkswagen|vw)\b/i],["Citroen",/\b(citroen|citroën)\b/i],["Vauxhall",/\bvauxhall\b/i],["Peugeot",/\bpeugeot\b/i],["Renault",/\brenault\b/i],["Nissan",/\bnissan\b/i],["Toyota",/\btoyota\b/i],["MAXUS",/\bmaxus\b/i],["Iveco",/\biveco\b/i],["Isuzu",/\bisuzu\b/i],["Fiat",/\bfiat\b/i],["Ford",/\bford\b/i],["MAN",/\bman\b/i],["LDV",/\bldv\b/i],["Hyundai",/\bhyundai\b/i],["Kia",/\bkia\b/i],["Mitsubishi",/\bmitsubishi\b/i],["Suzuki",/\bsuzuki\b/i],["Dacia",/\bdacia\b/i],["DFSK",/\bdfsk\b/i]];return rules.find(([,p])=>p.test(clean(text)))?.[0]||""}
function detectModel(make,text){const lower=clean(text).toLowerCase();if(make==="Ford"){if(/transit\s+custom|\bcustom\b/.test(lower))return "Transit Custom";if(/transit\s+connect|\bconnect\b/.test(lower))return "Transit Connect";if(/transit\s+courier|\bcourier\b/.test(lower))return "Transit Courier";if(/\btipper\b/.test(lower))return "Transit Tipper";if(/tourneo\s+custom/.test(lower))return "Tourneo Custom";if(/tourneo\s+connect/.test(lower))return "Tourneo Connect";if(/fiesta\s+van/.test(lower))return "Fiesta Van";if(/\branger\b/.test(lower))return "Ranger";if(/\btourneo\b/.test(lower))return "Tourneo";if(/\btransit\b/.test(lower))return "Transit";return ""}return (MODEL_RULES[make]||[]).find(m=>lower.includes(m.toLowerCase()))||""}
export default async function handler(req,res){try{const supabase=getSupabase();const [stock,wixRes]=await Promise.all([supabase.from("facebook_adverts").select("id,title,picture,price,vat,vanDescription,vanSpec,weblink,is_active").eq("is_active",true).limit(20),fetch(WIX_FINANCE_CMS_ENDPOINT,{headers:{Accept:"application/json"},cache:"no-store"})]);if(stock.error)throw stock.error;const payload=await wixRes.json();const map=new Map((payload.items||[]).map(i=>[registrationKey(i.registration),i]));const samples=(stock.data||[]).map(r=>{const reg=extractRegistration(r.title,r.weblink,r.vanDescription,r.vanSpec);const wix=map.get(reg)||null;const combined=[wix?.title,r.vanDescription,r.vanSpec].map(clean).join(" ");const make=detectMake(combined);const model=detectModel(make,combined);const year=parseYear(r.vanSpec,reg,wix?.title,r.vanDescription);const mileage=parseMileage(r.vanSpec,r.vanDescription,wix?.title);const price=parseMoney(r.price);const imageCount=Array.isArray(wix?.images)?wix.images.length:0;const missing=[['reg',reg],['wix',wix],['make',make],['model',model],['year',year],['mileage',mileage],['price',price],['images',imageCount]].filter(([,v])=>!v).map(([k])=>k);return {reg,wix:!!wix,wixTitle:wix?.title||"",make,model,supported:SUPPORTED_MAKES.has(make),year,mileage,price,imageCount,missing,vanSpec:r.vanSpec};});res.setHeader("Cache-Control","no-store");return res.status(200).json({ok:true,samples})}catch(e){return res.status(500).json({ok:false,error:e?.message||String(e)})}}
